=== irfankacapor/Semi-Structured-Data-Exercise-2/template/resources/shipment.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xhtml="http://www.w3.org/1999/xhtml">
  <xsd:element name="shipment" type="shipmentType">
    <xsd:key name="shipKey">
      <xsd:selector xpath="ships/ship"/>
      <xsd:field xpath="@sid"/>
    </xsd:key>
    <xsd:key name="tagKey">
      <xsd:selector xpath="tags/t"/>
      <xsd:field xpath="@tagname"/>
    </xsd:key>
    <xsd:key name="prodKey">
      <xsd:selector xpath="products/product"/>
      <xsd:field xpath="name"/>
      <xsd:field xpath="catalog"/>
    </xsd:key>

    <xsd:keyref name="sidRef" refer="shipKey">
      <xsd:selector xpath=".//ref"/>
      <xsd:field xpath="@sid"/>
    </xsd:keyref>
    <xsd:keyref name="tagRef" refer="tagKey">
      <xsd:selector xpath="ships/ship/tags/tag|products/product/tags/tag"/>
      <xsd:field xpath="."/>
    </xsd:keyref>

  </xsd:element>

  <xsd:complexType name="shipmentType">
    <xsd:all>
      <xsd:element name="ships" type="shipsType"/>
      <xsd:element name="products" type="productsType"/>
      <xsd:element name="tags" type="tagsTopType"/>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="shipsType">
    <xsd:sequence maxOccurs="unbounded">
      <xsd:element name="ship" type="shipType" />
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:complexType name="shipType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="info" type="infoType"/>
      <xsd:element name="tags" type="tagListType">
	<xsd:unique name="shipTagUniq">
	  <xsd:selector xpath="tag"/>
	  <xsd:field xpath="."/>
	</xsd:unique>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="sid" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="infoType">
    <xsd:attribute name="firstTour" type="xsd:date" use="required"/>
    <xsd:attribute name="lastTour" type="xsd:date"/>
    <xsd:attribute name="placeOfConstruction" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="tagListType">
    <xsd:sequence>
      <xsd:element name="tag" type="xsd:string"
		   minOccurs="0" maxOccurs="4" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="productsType">
    <xsd:sequence>
      <xsd:element name="product" type="productType" minOccurs="3" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  
  <xsd:complexType name="productType">
    <xsd:all>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="type" type="productTypeType"/>
      <xsd:element name="label" type="labelType"/>
      <xsd:element name="catalog" type="catType"/>
      <xsd:element name="tags" type="tagListType" minOccurs="0">
	<xsd:unique name="prodTagUniq">
	  <xsd:selector xpath="tag"/>
	  <xsd:field xpath="."/>
	</xsd:unique>
      </xsd:element>
    </xsd:all>
  </xsd:complexType>


  <xsd:complexType name="productTypeType">
    <xsd:choice maxOccurs="1">
      <xsd:element name="food" type="foodType"/>
      <xsd:element name="clothing" type="clothType"/>
    </xsd:choice>
  </xsd:complexType>

  <xsd:complexType name="foodType">
    <xsd:attribute name="foodType" type="foodTypeType" use="required"/>
    <xsd:attribute name="storageInfo" type="nonEmptyStr" use="required"/>
  </xsd:complexType>

  <xsd:simpleType name="nonEmptyStr">
    <xsd:restriction base="xsd:string">
      <xsd:minLength value="1"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="foodTypeType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Fruits"/>
      <xsd:enumeration value="Wine"/>
      <xsd:enumeration value="Meat"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="clothType">
    <xsd:attribute name="material"/>
  </xsd:complexType>
  
  <xsd:complexType name="labelType" mixed="true">
    <xsd:sequence>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
	<xsd:element name="destination" type="xsd:string" minOccurs="0"  maxOccurs="unbounded"/>
	<xsd:element name="ref" type="refType"  minOccurs="0"  maxOccurs="unbounded" />
      </xsd:choice>
      <xsd:element name="producer" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
	<xsd:element name="destination" type="xsd:string" minOccurs="0"  maxOccurs="unbounded"/>
	<xsd:element name="ref" type="refType"  minOccurs="0"  maxOccurs="unbounded" />
      </xsd:choice>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="refType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
	<xsd:attribute name="t" type="xsd:string"/>
	<xsd:attribute name="sid" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  
    <xsd:simpleType name="catType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[A-Z]{1}#[0-9]{4}#[a-g]{3}" />
    </xsd:restriction>
  </xsd:simpleType>


  <xsd:complexType name="tagsTopType">
    <xsd:sequence maxOccurs="unbounded">
      <xsd:element name="t" type="tType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="tType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
	<xsd:attribute name="tagname" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  
</xsd:schema>

=== irfankacapor/Semi-Structured-Data-Exercise-2/template/resources/shipment-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<shipment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="shipment.xsd">
  <ships>
    <ship sid="1">
      <name>Ship 1</name>
      <info firstTour="1981-10-25" lastTour="1993-04-07" placeOfConstruction="South Africa"/>
      <tags>
	<tag>Eduard Green</tag>
	<tag>Evelin Smith</tag>
	<tag>Sebastian Maxwell</tag>
	<tag>Thomas Blue</tag>
      </tags>
    </ship>
	<ship sid="2">
      <name>Ship 2</name>
      <info firstTour="1990-12-20" lastTour="2020-07-10" placeOfConstruction="Portugal"/>
      <tags>
	<tag>Evelin Smith</tag>
	<tag>Samantha Jones</tag>
      </tags>
    </ship>
	<ship sid="3">
      <name>Ship 3</name>
      <info firstTour="2000-01-01" lastTour="2023-04-15" placeOfConstruction="Chile"/>
      <tags>
	<tag>Robin Smith</tag>
	<tag>Noah Evans</tag>
      </tags>
    </ship>
	<ship sid="4">
      <name>Ship 4</name>
      <info firstTour="2023-03-15" placeOfConstruction="Germany"/>
      <tags>
	<tag>Sophie Taylor</tag>
	<tag>Sebastian Maxwell</tag>
      </tags>
    </ship>
  </ships>
  
  <products>
    <product>
      <name>Kiwi</name>
      <type><food foodType="Fruits" storageInfo="paper packaging"/></type>
      <label>
		This product was produced by <producer>EML</producer> and will be shipped to the <destination>UK</destination>, <destination>France</destination>, and <destination>Norway</destination>.
	    Currently <ref sid="1">Ship 1</ref> and <ref sid="2">Ship 2</ref> transport batches of this product.
      </label>
      <catalog>P#4525#bge</catalog>
      <tags>
	<tag>Eduard Green</tag>
	<tag>Evelin Smith</tag>
      </tags>
    </product>

    <product>
      <name>Beef</name>
      <type><food foodType="Meat" storageInfo="paperboard packaging"/></type>
	  <label>
		This product is produced by <producer>EML</producer> and will be shipped to the <destination>Germany</destination>.
      </label>
      <catalog>P#3525#age</catalog>
    </product>
	
	<product>
      <name>Zweigelt</name>
      <type><food foodType="Wine" storageInfo="paper packaging"/></type>
	  <label>
		This product is produced by <producer>EML</producer>.
      </label>
      <catalog>G#1224#abb</catalog>
    </product>

    <product>
      <name>Coat</name>
      <type><clothing material="plastic packaging"/></type>
	  <label>
		This product is produced by <producer>Zara</producer> and will be shipped to the <destination>Italy</destination>. 
		<ref sid="3">Ship 3</ref> currently carries a batch of this product.
      </label>
      <catalog>X#5555#cca</catalog>
    </product>
  </products>
    
  <tags>
    <t tagname="Eduard Green">
      Ship captain.
    </t>
    <t tagname="Samantha Jones">
      Ship captain.
    </t>
	<t tagname="Sophie Taylor">
      Ship captain.
    </t>
	<t tagname="Robin Smith">
      Ship captain.
    </t>
    <t tagname="Evelin Smith">
      Ship mate in training - assigned to multiple vessels.
    </t>
	<t tagname="Thomas Blue">
      Ship mate.
    </t>
	<t tagname="Noah Evans">
      Ship mate.
    </t>
	<t tagname="Sebastian Maxwell">
      Ship chef in training - assigned to multiple vessels.
    </t>
  </tags>
</shipment>

=== irfankacapor/Semi-Structured-Data-Exercise-2/template/output/shipment-sample-xsd-out.xml
<shipment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="shipment.xsd">
      
    <ships>
            
        <ship sid="1">
                  
            <name>Ship 1</name>
                  
            <info firstTour="1981-10-25" lastTour="1993-04-07" placeOfConstruction="South Africa"/>
                  
            <tags>
                	
                <tag>Evelin Smith</tag>
                	
                <tag>Sebastian Maxwell</tag>
                	
                <tag>Thomas Blue</tag>
                      
            </tags>
                
        </ship>
        	
        <ship sid="2">
                  
            <name>Ship 2</name>
                  
            <info firstTour="1990-12-20" lastTour="2020-07-10" placeOfConstruction="Portugal"/>
                  
            <tags>
                	
                <tag>Evelin Smith</tag>
                	
                <tag>Samantha Jones</tag>
                      
            </tags>
                
        </ship>
        	
        <ship sid="3">
                  
            <name>Ship 3</name>
                  
            <info firstTour="2000-01-01" lastTour="2023-04-15" placeOfConstruction="Chile"/>
                  
            <tags>
                	
                <tag>Robin Smith</tag>
                	
                <tag>Noah Evans</tag>
                      
            </tags>
                
        </ship>
        	
        <ship sid="4">
                  
            <name>Ship 4</name>
                  
            <info firstTour="2023-03-15" placeOfConstruction="Germany"/>
                  
            <tags>
                	
                <tag>Sophie Taylor</tag>
                	
                <tag>Sebastian Maxwell</tag>
                      
            </tags>
                
        </ship>
          
    </ships>
      
  
    <products>
            
        <product>
                  
            <name>Kiwi</name>
                  
            <type>
                <food foodType="Fruits" storageInfo="paper packaging"/>
            </type>
                  
            <label>
                		This product was produced by 
                <producer>EML</producer>
                 and will be shipped to the 
                <destination>UK</destination>
                , 
                <destination>France</destination>
                , and 
                <destination>Norway</destination>
                .
	    Currently 
                <ref sid="1">Ship 1</ref>
                 and 
                <ref sid="2">Ship 2</ref>
                 transport batches of this product.
      
            </label>
                  
            <catalog>P#4525#bge</catalog>
                  
            <tags>
                	
                <tag>Eduard Green</tag>
                	
                <tag>Evelin Smith</tag>
                      
            </tags>
                
        </product>
            
        <product>
                  
            <name>Beef</name>
                  
            <type>
                <food foodType="Meat" storageInfo="paperboard packaging"/>
            </type>
            	  
            <label>
                		This product is produced by 
                <producer>EML</producer>
                 and will be shipped to the 
                <destination>Germany</destination>
                .
      
            </label>
                  
            <catalog>P#3525#age</catalog>
                  
            <tags>
                	
                <tag>Sebastian Maxwell</tag>
                      
            </tags>
                
        </product>
        	
	
        <product>
                  
            <name>Zweigelt</name>
                  
            <type>
                <food foodType="Wine" storageInfo="paper packaging"/>
            </type>
            	  
            <label>
                		This product is produced by 
                <producer>EML</producer>
                . 
      
            </label>
                  
            <catalog>G#1224#abb</catalog>
                
        </product>
            
  
        <product>
            <name>Banana</name>
            <type>
                <food foodType="Fruits" storageInfo="paper packaging"/>
            </type>
            <label>
                <producer>BR</producer>
                 and will be shipped to the 
                <destination>UK</destination>
                . Currently 
                <ref sid="3">Ship 3</ref>
                 carries a batch of this product. A banana is an elongated, edible fruit - botanically a berry - produced by several kinds of large herbaceous flowering plants in the genus Musa.
            </label>
            <catalog>E#1637#aaa</catalog>
            <tags/>
        </product>
        <product>
            <name>Chianti</name>
            <type>
                <food foodType="Wine" storageInfo="paper packaging"/>
            </type>
            <label>
                <producer>Super Tuscans</producer>
                 and will be shipped to the 
                <destination>Japan</destination>
                . Currently 
                <ref sid="4">Ship 4</ref>
                 carries a batch of this product. A Chianti wine is any wine produced in the Chianti region of central Tuscany. 
            </label>
            <catalog>E#5895#aaa</catalog>
            <tags>
                <tag>Italy</tag>
            </tags>
        </product>
        <product>
            <name>Jeans</name>
            <type>
                <clothing/>
            </type>
            <label>
                <producer>Levis</producer>
                 and will be shipped to the 
                <destination>France</destination>
                . Currently 
                <ref sid="2">Ship 2</ref>
                 carries a batch of this product. Often the term "jeans" refers to a particular style of trousers, called "blue jeans", with copper-riveted pockets which were invented by Jacob W. Davis in 1871 and patented by Jacob W. Davis and Levi Strauss on May 20, 1873.  
            </label>
            <catalog>E#4751#aaa</catalog>
            <tags>
                <tag>Eduard Green</tag>
            </tags>
        </product>
    </products>
        
  
    <tags>
            
        <t tagname="Eduard Green">
      Ship captain.
    </t>
            
        <t tagname="Samantha Jones"/>
        	
        <t tagname="Sophie Taylor">
      Ship captain.
    </t>
        	
        <t tagname="Robin Smith">
      Ship captain.
    </t>
            
        <t tagname="Evelin Smith">
      Ship mate in training - assigned to multiple vessels.
    </t>
        	
        <t tagname="Thomas Blue">
      Ship mate.
    </t>
        	
        <t tagname="Noah Evans">
      Ship mate.
    </t>
        	
        <t tagname="Sebastian Maxwell">
      Ship chef in training - assigned to multiple vessels.
    </t>
          
        <t tagname="Italy"/>
    </tags>
    
</shipment>
